export const editSignals = [
  // English — direct edit verbs
  "edit",
  "change",
  "update",
  "modify",
  "rewrite",
  "adjust",
  "revise",
  "rework",
  "refine",
  "fix",
  "correct",
  "improve",
  "customize",
  "adapt",
  "convert",
  "transform",
  "swap",
  "replace",
  "substitute",
  "remove",
  "delete",
  "omit",
  "exclude",
  "add",
  "include",
  "put in",
  "mix in",

  // English — recipe-directed edit phrases
  "edit the recipe",
  "change the recipe",
  "update the recipe",
  "modify the recipe",
  "rewrite the recipe",
  "adjust the recipe",
  "revise the recipe",
  "fix the recipe",
  "customize the recipe",
  "adapt the recipe",
  "convert the recipe",
  "make this recipe",
  "turn this recipe into",
  "change this recipe to",
  "update this recipe to",
  "rewrite this recipe as",

  // English — ingredient/substitution phrasing
  "instead of",
  "use ... instead",
  "replace with",
  "swap for",
  "substitute with",
  "without",
  "with no",
  "with less",
  "with more",
  "make it with",
  "make this with",
  "do it with",
  "i want it with",
  "i want this with",
  "i want it without",
  "i want this without",
  "can you make it with",
  "can you make it without",
  "can you change it to",
  "make it sweeter",
  "make it less sweet",
  "make it spicier",
  "make it less spicy",
  "make it milder",
  "make it healthier",
  "make it lighter",
  "make it richer",
  "make it crispier",
  "make it softer",
  "make it easier",
  "make it simpler",
  "make it quicker",
  "make it shorter",
  "make it cheaper",
  "make it lower carb",
  "make it low carb",
  "make it high protein",
  "make it vegetarian",
  "make it vegan",
  "make it dairy free",
  "make it lactose free",
  "make it gluten free",
  "make it sugar free",
  "make it less salty",
  "make it more salty",
  "make it less oily",
  "make it more saucy",

  // English — quantity / structure edits
  "more protein",
  "less sugar",
  "less salt",
  "less oil",
  "more sauce",
  "different ingredients",
  "different seasoning",
  "different sauce",
  "shorter instructions",
  "simpler instructions",
  "change the ingredients",
  "change the instructions",
  "change the sauce",
  "change the seasoning",
  "double the recipe",
  "halve the recipe",
  "scale the recipe",
  "reduce the servings",
  "increase the servings",

  // Hebrew — direct edit verbs
  "ערוך",
  "לערוך",
  "תערוך",
  "תערכי",
  "ערכי",
  "שנה",
  "לשנות",
  "תשנה",
  "תשני",
  "שני",
  "עדכן",
  "לעדכן",
  "תעדכן",
  "תעדכני",
  "עדכני",
  "תקן",
  "לתקן",
  "תתקן",
  "תתקני",
  "תקני",
  "שדרג",
  "לשדרג",
  "תשדרג",
  "תשדרגי",
  "שדרגי",
  "שפר",
  "לשפר",
  "תשפר",
  "תשפרי",
  "שפרי",
  "תאים",
  "להתאים",
  "תתאים",
  "תתאימי",
  "התאם",
  "התאימי",
  "המר",
  "להמיר",
  "תמיר",
  "תמירי",
  "הפוך",
  "להפוך",
  "תהפוך",
  "תהפכי",

  // Hebrew — add/remove/replace
  "תוסיף",
  "תוסיפי",
  "להוסיף",
  "הוסף",
  "הוסיפי",
  "תוריד",
  "תורידי",
  "להוריד",
  "הורד",
  "הורידי",
  "תחליף",
  "תחליפי",
  "להחליף",
  "החלף",
  "החליפי",
  "שים במקום",
  "שימי במקום",
  "במקום",
  "במקום ה",
  "עם",
  "בלי",
  "ללא",
  "עם פחות",
  "עם יותר",
  "תעשה עם",
  "תעשי עם",
  "תכין עם",
  "תכיני עם",
  "תעשה בלי",
  "תעשי בלי",
  "תכין בלי",
  "תכיני בלי",

  // Hebrew — explicit recipe edit phrases
  "תשנה את המתכון",
  "תשני את המתכון",
  "תערוך את המתכון",
  "תערכי את המתכון",
  "תעדכן את המתכון",
  "תעדכני את המתכון",
  "תתקן את המתכון",
  "תתקני את המתכון",
  "תשדרג את המתכון",
  "תשדרגי את המתכון",
  "תשפר את המתכון",
  "תשפרי את המתכון",
  "תתאים את המתכון",
  "תתאימי את המתכון",
  "תמיר את המתכון",
  "תמירי את המתכון",
  "תהפוך את המתכון",
  "תהפכי את המתכון",
  "שנה את המתכון",
  "ערוך את המתכון",
  "עדכן את המתכון",
  "תקן את המתכון",
  "שדרג את המתכון",
  "שפר את המתכון",
  "התאם את המתכון",
  "המר את המתכון",

  // Hebrew — natural preference/edit phrasing
  "אני רוצה עם",
  "אני רוצה בלי",
  "אני רוצה פחות",
  "אני רוצה יותר",
  "אני רוצה שזה יהיה",
  "אני רוצה שיהיה",
  "בא לי עם",
  "בא לי בלי",
  "אפשר עם",
  "אפשר בלי",
  "אפשר לעשות עם",
  "אפשר לעשות בלי",
  "אפשר להכין עם",
  "אפשר להכין בלי",
  "אני מעדיף עם",
  "אני מעדיפה עם",
  "אני מעדיף בלי",
  "אני מעדיפה בלי",
  "תעשה את זה עם",
  "תעשי את זה עם",
  "תעשה את זה בלי",
  "תעשי את זה בלי",
  "תכין את זה עם",
  "תכיני את זה עם",
  "תכין את זה בלי",
  "תכיני את זה בלי",

  // Hebrew — taste / nutrition / dietary changes
  "יותר מתוק",
  "פחות מתוק",
  "יותר חריף",
  "פחות חריף",
  "יותר מלוח",
  "פחות מלוח",
  "יותר חמוץ",
  "פחות חמוץ",
  "יותר שום",
  "פחות שום",
  "יותר רוטב",
  "פחות רוטב",
  "יותר חלבון",
  "פחות סוכר",
  "פחות מלח",
  "פחות שמן",
  "פחות קלוריות",
  "יותר קליל",
  "יותר בריא",
  "יותר דיאטטי",
  "פחות שמנוני",
  "פחות כבד",
  "יותר עסיסי",
  "יותר קריספי",
  "פחות חרוך",

  // Hebrew — dietary conversions
  "תעשה טבעוני",
  "תעשי טבעוני",
  "תהפוך לטבעוני",
  "תהפכי לטבעוני",
  "תעשה צמחוני",
  "תעשי צמחוני",
  "תעשה ללא גלוטן",
  "תעשי ללא גלוטן",
  "בלי גלוטן",
  "ללא גלוטן",
  "תעשה בלי גלוטן",
  "תעשי בלי גלוטן",
  "תעשה ללא לקטוז",
  "תעשי ללא לקטוז",
  "בלי לקטוז",
  "ללא לקטוז",
  "תעשה בלי לקטוז",
  "תעשי בלי לקטוז",
  "ללא סוכר",
  "בלי סוכר",
  "פחות סוכר",
  "תעשה ללא סוכר",
  "תעשי ללא סוכר",
  "דל פחמימה",
  "פחות פחמימות",
  "עתיר חלבון",
  "יותר חלבון",

  // Hebrew — ingredient list / instruction edits
  "מרכיבים אחרים",
  "מרכיב אחר",
  "תחליף את המרכיבים",
  "תחליפי את המרכיבים",
  "תשנה את המרכיבים",
  "תשני את המרכיבים",
  "תעדכן את המרכיבים",
  "תעדכני את המרכיבים",
  "תקצר את ההוראות",
  "תקצרי את ההוראות",
  "תשנה את ההוראות",
  "תשני את ההוראות",
  "תעדכן את ההוראות",
  "תעדכני את ההוראות",
  "תפשט את ההוראות",
  "תפשטי את ההוראות",
  "תעשה את זה פשוט יותר",
  "תעשי את זה פשוט יותר",
  "תקצר את המתכון",
  "תקצרי את המתכון",
  "תפשט את המתכון",
  "תפשטי את המתכון",

  // Hebrew — quantity / servings
  "תכפיל את הכמות",
  "תכפילי את הכמות",
  "תקטין את הכמות",
  "תקטיני את הכמות",
  "תגדיל את הכמות",
  "תגדילי את הכמות",
  "ליותר מנות",
  "לפחות מנות",
  "לכמה מנות",
  "תתאים ל",
  "תתאימי ל",
  "למנה אחת",
  "לשתי מנות",
  "לארבע מנות",
  "ליותר אנשים",
  "לפחות אנשים"
];