export function getCountryFlag(countryName: string): string | undefined {
  switch (countryName) {
    case "Algeria": return "🇩🇿";
    case "Bahrain": return "🇧🇭";
    case "Comoros": return "🇰🇲";
    case "Djibouti": return "🇩🇯";
    case "Egypt": return "🇪🇬";
    case "Iraq": return "🇮🇶";
    case "Jordan": return "🇯🇴";
    case "Kuwait": return "🇰🇼";
    case "Lebanon": return "🇱🇧";
    case "Libya": return "🇱🇾";
    case "Mauritania": return "🇲🇷";
    case "Morocco": return "🇲🇦";
    case "Oman": return "🇴🇲";
    case "Palestine": return "🇵🇸";
    case "Qatar": return "🇶🇦";
    case "Saudi Arabia": return "🇸🇦";
    case "Somalia": return "🇸🇴";
    case "Sudan": return "🇸🇩";
    case "Syria": return "🇸🇾";
    case "Tunisia": return "🇹🇳";
    case "United Arab Emirates": return "🇦🇪";
    case "Yemen": return "🇾🇪";
    case "UAE": return "🇦🇪";
    case "KSA": return "🇸🇦";
    case "Turkey": return "🇹🇷";
    case "Iran": return "🇮🇷";
    case "Israel": return "🇮🇱";
    case "Cyprus": return "🇨🇾";
    case "Italy": return "🇮🇹";
    case "France": return "🇫🇷";
    case "Spain": return "🇪🇸";
    case "Portugal": return "🇵🇹";
    case "Greece": return "🇬🇷";
    case "Germany": return "🇩🇪";
    case "Switzerland": return "🇨🇭";
    case "Austria": return "🇦🇹";
    case "United Kingdom": return "🇬🇧";
    case "UK": return "🇬🇧";
    case "Ireland": return "🇮🇪";
    case "Netherlands": return "🇳🇱";
    case "Belgium": return "🇧🇪";
    case "Luxembourg": return "🇱🇺";
    case "Denmark": return "🇩🇰";
    case "Sweden": return "🇸🇪";
    case "Norway": return "🇳🇴";
    case "Finland": return "🇫🇮";
    case "Iceland": return "🇮🇸";
    case "Poland": return "🇵🇱";
    case "Czechia": return "🇨🇿";
    case "Czech Republic": return "🇨🇿";
    case "Slovakia": return "🇸🇰";
    case "Hungary": return "🇭🇺";
    case "Romania": return "🇷🇴";
    case "Bulgaria": return "🇧🇬";
    case "Croatia": return "🇭🇷";
    case "Serbia": return "🇷🇸";
    case "Slovenia": return "🇸🇮";
    case "Bosnia and Herzegovina": return "🇧🇦";
    case "Bosnia": return "🇧🇦";
    case "North Macedonia": return "🇲🇰";
    case "Macedonia": return "🇲🇰";
    case "Albania": return "🇦🇱";
    case "Kosovo": return "🇽🇰";
    case "Ukraine": return "🇺🇦";
    case "Russia": return "🇷🇺";
    case "Belarus": return "🇧🇾";
    case "Estonia": return "🇪🇪";
    case "Latvia": return "🇱🇻";
    case "Lithuania": return "🇱🇹";
    case "United States": return "🇺🇸";
    case "United States of America": return "🇺🇸";
    case "USA": return "🇺🇸";
    case "US": return "🇺🇸";
    case "Canada": return "🇨🇦";
    case "Mexico": return "🇲🇽";
    case "Guatemala": return "🇬🇹";
    case "Cuba": return "🇨🇺";
    case "Dominican Republic": return "🇩🇴";
    case "Haiti": return "🇭🇹";
    case "Jamaica": return "🇯🇲";
    case "Brazil": return "🇧🇷";
    case "Argentina": return "🇦🇷";
    case "Chile": return "🇨🇱";
    case "Peru": return "🇵🇪";
    case "Colombia": return "🇨🇴";
    case "Venezuela": return "🇻🇪";
    case "Ecuador": return "🇪🇨";
    case "Bolivia": return "🇧🇴";
    case "Uruguay": return "🇺🇾";
    case "Paraguay": return "🇵🇾";
    case "China": return "🇨🇳";
    case "Japan": return "🇯🇵";
    case "South Korea": return "🇰🇷";
    case "Republic of Korea": return "🇰🇷";
    case "North Korea": return "🇰🇵";
    case "Thailand": return "🇹🇭";
    case "Vietnam": return "🇻🇳";
    case "Cambodia": return "🇰🇭";
    case "Laos": return "🇱🇦";
    case "Malaysia": return "🇲🇾";
    case "Singapore": return "🇸🇬";
    case "Indonesia": return "🇮🇩";
    case "Philippines": return "🇵🇭";
    case "Myanmar": return "🇲🇲";
    case "Sri Lanka": return "🇱🇰";
    case "India": return "🇮🇳";
    case "Pakistan": return "🇵🇰";
    case "Bangladesh": return "🇧🇩";
    case "Nepal": return "🇳🇵";
    case "Bhutan": return "🇧🇹";
    case "Mongolia": return "🇲🇳";
    case "Kazakhstan": return "🇰🇿";
    case "Uzbekistan": return "🇺🇿";
    case "Turkmenistan": return "🇹🇲";
    case "Tajikistan": return "🇹🇯";
    case "Kyrgyzstan": return "🇰🇬";
    case "Afghanistan": return "🇦🇫";
    case "Nigeria": return "🇳🇬";
    case "Ghana": return "🇬🇭";
    case "Kenya": return "🇰🇪";
    case "Ethiopia": return "🇪🇹";
    case "Tanzania": return "🇹🇿";
    case "Uganda": return "🇺🇬";
    case "Rwanda": return "🇷🇼";
    case "South Africa": return "🇿🇦";
    case "Namibia": return "🇳🇦";
    case "Zimbabwe": return "🇿🇼";
    case "Zambia": return "🇿🇲";
    case "Botswana": return "🇧🇼";
    case "Senegal": return "🇸🇳";
    case "Ivory Coast": return "🇨🇮";
    case "Côte d'Ivoire": return "🇨🇮";
    case "Cameroon": return "🇨🇲";
    case "Mali": return "🇲🇱";
    case "Australia": return "🇦🇺";
    case "New Zealand": return "🇳🇿";
    case "Fiji": return "🇫🇯";
    case "Papua New Guinea": return "🇵🇬";
    default: return undefined;
  }
}

export function flagEmojiToTwemojiUrl(flag: string): string {
  // flag is two regional-indicator codepoints (e.g. 🇮🇱)
  const codepoints = Array.from(flag)
    .map(ch => ch.codePointAt(0)!.toString(16))
    .join("-");
  return `https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/${codepoints}.svg`;
}